/****** TOW WITH VEHICLE  ******/

/**
 * List of class names of (ground or air) vehicles which can tow towables objects.
 */
R3F_LOG_CFG_remorqueurs =
[
	"SUV_01_base_F",
	"Offroad_01_base_F",
	"Van_01_base_F",
	"MRAP_01_base_F",
	"MRAP_02_base_F",
	"MRAP_03_base_F",
	"Truck_01_base_F",
	"Truck_02_base_F",
	"Truck_03_base_F",
	"Wheeled_APC_F",
	"Tank_F",
	"I_mas_BRDM2",
	"I_mas_BTR60",
	"O_mas_BRDM2",
	"O_mas_BTR60",
	"I_mas_cars_UAZ_MG",
	"I_mas_cars_UAZ_AGS30",
	"I_mas_cars_UAZ_SPG9",
	"I_mas_cars_UAZ_Unarmed",
	"I_mas_cars_UAZ_Med",
	"I_mas_cars_UAZ_M2",
	"O_mas_cars_UAZ_MG",
	"O_mas_cars_UAZ_AGS30",
	"O_mas_cars_UAZ_SPG9",
	"O_mas_cars_UAZ_Unarmed",
	"O_mas_cars_UAZ_Med",
	"B_mas_cars_Hilux_MG",
	"B_mas_cars_Hilux_AGS30",
	"B_mas_cars_Hilux_SPG9",
	"B_mas_cars_Hilux_RKTS",
	"B_mas_cars_Hilux_Unarmed",
	"B_mas_cars_Hilux_Med",
	"B_mas_cars_Hilux_M2",
	"B_mas_cars_LR_Unarmed",
	"B_mas_cars_LR_Med",
	"B_mas_cars_LR_M2",
	"B_mas_cars_LR_Mk19",
	"B_mas_cars_LR_TOW",
	"B_mas_cars_LR_Stinger",
	"B_mas_cars_LR_SPG9",
	"I_mas_cars_LR_soft_Unarmed",
	"I_mas_cars_LR_soft_Med",
	"I_mas_cars_LR_soft_M2",
	"I_mas_cars_LR_soft_Mk19",
	"I_mas_cars_LR_soft_TOW",
	"I_mas_cars_LR_soft_Stinger",
	"I_mas_cars_LR_soft_SPG9",
	"B_mas_HMMWV_M2",
	"B_mas_HMMWV_M134",
	"B_mas_HMMWV_SOV",
	"B_mas_HMMWV_SOV_M134",
	"B_mas_HMMWV_TOW",
	"B_mas_HMMWV_Stinger",
	"B_mas_HMMWV_MK19",
	"B_mas_HMMWV_UNA",
	"B_mas_HMMWV_MEV",
	"B_mas_HMMWV_M2_des",
	"B_mas_HMMWV_M134_des",
	"B_mas_HMMWV_SOV_des",
	"B_mas_HMMWV_SOV_M134_des",
	"B_mas_HMMWV_TOW_des",
	"B_mas_HMMWV_Stinger_des",
	"B_mas_HMMWV_MK19_des",
	"B_mas_HMMWV_UNA_des",
	"B_mas_HMMWV_MEV_des",
	"I_mas_cars_Ural",
	"I_mas_cars_Ural_open",
	"I_mas_cars_Ural_ammo",
	"I_mas_cars_Ural_repair",
	"I_mas_cars_Ural_fuel",
	"I_mas_cars_Ural_BM21",
	"I_mas_cars_Ural_ZU23",
	"O_mas_cars_Ural",
	"O_mas_cars_Ural_open",
	"O_mas_cars_Ural_ammo",
	"O_mas_cars_Ural_repair",
	"O_mas_cars_Ural_fuel",
	"O_mas_cars_Ural_BM21",
	"O_mas_cars_Ural_ZU23",
	"Boat_Armed_01_base_F"
];

/**
 * List of class names of towables objects.
 */
R3F_LOG_CFG_objets_remorquables =
[
	"Hatchback_01_base_F",
	"SUV_01_base_F",
	"Offroad_01_base_F",
	"Van_01_base_F",
	"MRAP_01_base_F",
	"MRAP_02_base_F",
	"MRAP_03_base_F",
	"UGV_01_base_F",
	"SDV_01_base_F",
	"Boat_Civil_01_base_F",
	"Boat_Armed_01_base_F",
	"Helicopter_Base_F",
	"I_mas_cars_UAZ_MG",
	"I_mas_cars_UAZ_AGS30",
	"I_mas_cars_UAZ_SPG9",
	"I_mas_cars_UAZ_Unarmed",
	"I_mas_cars_UAZ_Med",
	"I_mas_cars_UAZ_M2",
	"O_mas_cars_UAZ_MG",
	"O_mas_cars_UAZ_AGS30",
	"O_mas_cars_UAZ_SPG9",
	"O_mas_cars_UAZ_Unarmed",
	"O_mas_cars_UAZ_Med",
	"B_mas_cars_Hilux_MG",
	"B_mas_cars_Hilux_AGS30",
	"B_mas_cars_Hilux_SPG9",
	"B_mas_cars_Hilux_RKTS",
	"B_mas_cars_Hilux_Unarmed",
	"B_mas_cars_Hilux_Med",
	"B_mas_cars_Hilux_M2",
	"B_mas_cars_LR_Unarmed",
	"B_mas_cars_LR_Med",
	"B_mas_cars_LR_M2",
	"B_mas_cars_LR_Mk19",
	"B_mas_cars_LR_TOW",
	"B_mas_cars_LR_Stinger",
	"B_mas_cars_LR_SPG9",
	"I_mas_cars_LR_soft_Unarmed",
	"I_mas_cars_LR_soft_Med",
	"I_mas_cars_LR_soft_M2",
	"I_mas_cars_LR_soft_Mk19",
	"I_mas_cars_LR_soft_TOW",
	"I_mas_cars_LR_soft_Stinger",
	"I_mas_cars_LR_soft_SPG9",
	"B_mas_HMMWV_M2",
	"B_mas_HMMWV_M134",
	"B_mas_HMMWV_SOV",
	"B_mas_HMMWV_SOV_M134",
	"B_mas_HMMWV_TOW",
	"B_mas_HMMWV_Stinger",
	"B_mas_HMMWV_MK19",
	"B_mas_HMMWV_UNA",
	"B_mas_HMMWV_MEV",
	"B_mas_HMMWV_M2_des",
	"B_mas_HMMWV_M134_des",
	"B_mas_HMMWV_SOV_des",
	"B_mas_HMMWV_SOV_M134_des",
	"B_mas_HMMWV_TOW_des",
	"B_mas_HMMWV_Stinger_des",
	"B_mas_HMMWV_MK19_des",
	"B_mas_HMMWV_UNA_des",
	"B_mas_HMMWV_MEV_des",
	"I_mas_cars_Ural",
	"I_mas_cars_Ural_open",
	"I_mas_cars_Ural_ammo",
	"I_mas_cars_Ural_repair",
	"I_mas_cars_Ural_fuel",
	"I_mas_cars_Ural_BM21",
	"I_mas_cars_Ural_ZU23",
	"O_mas_cars_Ural",
	"O_mas_cars_Ural_open",
	"O_mas_cars_Ural_ammo",
	"O_mas_cars_Ural_repair",
	"O_mas_cars_Ural_fuel",
	"O_mas_cars_Ural_BM21",
	"O_mas_cars_Ural_ZU23",
	"Plane"
];

/****** LIFT WITH VEHICLE  ******/

/**
 * List of class names of air vehicles which can lift liftables objects.
 */
R3F_LOG_CFG_heliporteurs =
[
	"Helicopter_Base_F",
	"I_mas_MI8",
	"I_mas_MI8MTV",
	"O_mas_MI8",
	"O_mas_MI8MTV"
];

/**
 * List of class names of liftables objects.
 */
R3F_LOG_CFG_objets_heliportables =
[
	"Hatchback_01_base_F",
	"SUV_01_base_F",
	"Offroad_01_base_F",
	"Land_ConcretePipe_F",
	"Van_01_base_F",
	"MRAP_01_base_F",
	"MRAP_02_base_F",
	"MRAP_03_base_F",
	"UGV_01_base_F",
	"Land_Cargo40_blue_F",
	"Land_Cargo40_brick_red_F",
	"Land_Cargo40_cyan_F",
	"Land_Cargo40_grey_F",
	"Land_Cargo40_light_blue_F",
	"Land_Cargo40_light_green_F",
	"Land_Cargo40_military_green_F",
	"Land_Cargo40_red_F",
	"Land_Cargo40_orange_F",
	"Land_Cargo40_sand_F",
	"Land_Cargo40_white_F",
	"Land_Cargo40_yellow_F",
	"I_mas_BRDM2",
	"I_mas_BTR60",
	"O_mas_BRDM2",
	"O_mas_BTR60",
	"I_mas_cars_UAZ_MG",
	"I_mas_cars_UAZ_AGS30",
	"I_mas_cars_UAZ_SPG9",
	"I_mas_cars_UAZ_Unarmed",
	"I_mas_cars_UAZ_Med",
	"I_mas_cars_UAZ_M2",
	"O_mas_cars_UAZ_MG",
	"O_mas_cars_UAZ_AGS30",
	"O_mas_cars_UAZ_SPG9",
	"O_mas_cars_UAZ_Unarmed",
	"O_mas_cars_UAZ_Med",
	"B_mas_cars_Hilux_MG",
	"B_mas_cars_Hilux_AGS30",
	"B_mas_cars_Hilux_SPG9",
	"B_mas_cars_Hilux_RKTS",
	"B_mas_cars_Hilux_Unarmed",
	"B_mas_cars_Hilux_Med",
	"B_mas_cars_Hilux_M2",
	"B_mas_cars_LR_Unarmed",
	"B_mas_cars_LR_Med",
	"B_mas_cars_LR_M2",
	"B_mas_cars_LR_Mk19",
	"B_mas_cars_LR_TOW",
	"B_mas_cars_LR_Stinger",
	"B_mas_cars_LR_SPG9",
	"I_mas_cars_LR_soft_Unarmed",
	"I_mas_cars_LR_soft_Med",
	"I_mas_cars_LR_soft_M2",
	"I_mas_cars_LR_soft_Mk19",
	"I_mas_cars_LR_soft_TOW",
	"I_mas_cars_LR_soft_Stinger",
	"I_mas_cars_LR_soft_SPG9",
	"B_mas_HMMWV_M2",
	"B_mas_HMMWV_M134",
	"B_mas_HMMWV_SOV",
	"B_mas_HMMWV_SOV_M134",
	"B_mas_HMMWV_TOW",
	"B_mas_HMMWV_Stinger",
	"B_mas_HMMWV_MK19",
	"B_mas_HMMWV_UNA",
	"B_mas_HMMWV_MEV",
	"B_mas_HMMWV_M2_des",
	"B_mas_HMMWV_M134_des",
	"B_mas_HMMWV_SOV_des",
	"B_mas_HMMWV_SOV_M134_des",
	"B_mas_HMMWV_TOW_des",
	"B_mas_HMMWV_Stinger_des",
	"B_mas_HMMWV_MK19_des",
	"B_mas_HMMWV_UNA_des",
	"B_mas_HMMWV_MEV_des",
	"I_mas_cars_Ural",
	"I_mas_cars_Ural_open",
	"I_mas_cars_Ural_ammo",
	"I_mas_cars_Ural_repair",
	"I_mas_cars_Ural_fuel",
	"I_mas_cars_Ural_BM21",
	"I_mas_cars_Ural_ZU23",
	"O_mas_cars_Ural",
	"O_mas_cars_Ural_open",
	"O_mas_cars_Ural_ammo",
	"O_mas_cars_Ural_repair",
	"O_mas_cars_Ural_fuel",
	"O_mas_cars_Ural_BM21",
	"O_mas_cars_Ural_ZU23",
	"I_mas_ZU23_AAF",
  "I_mas_D30_AAF",
  "I_mas_D30_AT_AAF",
	"I_mas_M119_AAF",
	"I_mas_M119_AT_AAF",
  "O_mas_ZU23_AAF",
	"O_mas_D30_AAF",
	"O_mas_D30_AT_AAF",
	"B_mas_M119_AAF",
	"B_mas_M119_AT_AAF",
	"B_mas_ZU23_FIA",
	"B_mas_D30_FIA",
  "B_mas_D30_AT_FIA",
	"SDV_01_base_F",
	"Boat_Civil_01_base_F",
	"Boat_Armed_01_base_F"
];


/****** LOAD IN VEHICLE / CHARGER DANS LE VEHICULE ******/


/**
 * List of class names of (ground or air) vehicles which can transport transportables objects.
 * The second element of the arrays is the load capacity (in relation with the capacity cost of the objects).
 */
R3F_LOG_CFG_transporteurs =
[
	["Quadbike_01_base_F", 5],
	["UGV_01_base_F", 10],
	["Hatchback_01_base_F", 10],
	["SUV_01_base_F", 20],
	["Offroad_01_base_F", 30],
	["I_mas_cars_UAZ_MG", 20],
	["I_mas_cars_UAZ_AGS30", 20],
	["I_mas_cars_UAZ_SPG9", 20],
	["I_mas_cars_UAZ_Unarmed", 20],
	["I_mas_cars_UAZ_Med", 20],
	["I_mas_cars_UAZ_M2", 20],
	["O_mas_cars_UAZ_MG", 20],
	["O_mas_cars_UAZ_AGS30", 20],
	["O_mas_cars_UAZ_SPG9", 20],
	["O_mas_cars_UAZ_Unarmed", 20],
	["O_mas_cars_UAZ_Med", 20],
	["B_mas_cars_Hilux_MG", 30],
	["B_mas_cars_Hilux_AGS30", 30],
	["B_mas_cars_Hilux_SPG9", 30],
	["B_mas_cars_Hilux_RKTS", 30],
	["B_mas_cars_Hilux_Unarmed", 30],
	["B_mas_cars_Hilux_Med", 30],
	["B_mas_cars_Hilux_M2", 30],
	["B_mas_cars_LR_Unarmed", 35],
	["B_mas_cars_LR_Med", 35],
	["B_mas_cars_LR_M2", 35],
	["B_mas_cars_LR_Mk19", 35],
	["B_mas_cars_LR_TOW", 35],
	["B_mas_cars_LR_Stinger", 35],
	["B_mas_cars_LR_SPG9", 35],
	["I_mas_cars_LR_soft_Unarmed", 35],
	["I_mas_cars_LR_soft_Med", 35],
	["I_mas_cars_LR_soft_M2", 35],
	["I_mas_cars_LR_soft_Mk19", 35],
	["I_mas_cars_LR_soft_TOW", 35],
	["I_mas_cars_LR_soft_Stinger", 35],
	["I_mas_cars_LR_soft_SPG9", 35],
	["B_mas_HMMWV_M2", 35],
	["B_mas_HMMWV_M134", 35],
	["B_mas_HMMWV_SOV", 35],
	["B_mas_HMMWV_SOV_M134", 35],
	["B_mas_HMMWV_TOW", 35],
	["B_mas_HMMWV_Stinger", 35],
	["B_mas_HMMWV_MK19", 35],
	["B_mas_HMMWV_UNA", 35],
	["B_mas_HMMWV_MEV", 35],
	["B_mas_HMMWV_M2_des", 35],
	["B_mas_HMMWV_M134_des", 35],
	["B_mas_HMMWV_SOV_des", 35],
	["B_mas_HMMWV_SOV_M134_des", 35],
	["B_mas_HMMWV_TOW_des", 35],
	["B_mas_HMMWV_Stinger_des", 35],
	["B_mas_HMMWV_MK19_des", 35],
	["B_mas_HMMWV_UNA_des", 35],
	["B_mas_HMMWV_MEV_des", 35],
	["I_mas_cars_Ural", 50],
	["I_mas_cars_Ural_open", 55],
	["I_mas_cars_Ural_ammo", 45],
	["I_mas_cars_Ural_repair", 45],
	["I_mas_cars_Ural_BM21", 35],
	["I_mas_cars_Ural_ZU23", 35],
	["O_mas_cars_Ural", 50],
	["O_mas_cars_Ural_open", 55],
	["O_mas_cars_Ural_ammo", 45],
	["O_mas_cars_Ural_repair", 45],
	["O_mas_cars_Ural_BM21", 35],
	["O_mas_cars_Ural_ZU23", 35],
	["I_mas_MI8", 50],
	["I_mas_MI8MTV", 45],
	["O_mas_MI8", 50],
	["O_mas_MI8MTV", 45],
	["B_mas_CH_47F", 75],
	["B_mas_UH1Y_F", 35],
	["B_mas_UH1Y_UNA_F", 35],
	["B_mas_UH60M_MEV", 35],
	["Van_01_base_F", 40],
	["MRAP_01_base_F", 20],
	["MRAP_02_base_F", 20],
	["MRAP_03_base_F", 20],
	["B_Truck_01_box_F", 150],
	["Truck_F", 75],
	["Land_Pod_Heli_Transport_04_box_F", 250],
	["Land_Pod_Heli_Transport_04_box_black_F", 250],
	["Land_Cargo40_blue_F", 500],
	["Land_Cargo40_brick_red_F", 500],
	["Land_Cargo40_cyan_F", 500],
	["Land_Cargo40_grey_F", 500],
	["Land_Cargo40_light_blue_F", 500],
	["Land_Cargo40_light_green_F", 500],
	["Land_Cargo40_military_green_F", 500],
	["Land_Cargo40_orange_F", 500],
	["Land_Cargo40_red_F", 500],
	["Land_Cargo40_sand_F", 500],
	["Land_Cargo40_white_F", 500],
	["Land_Cargo40_yellow_F", 500],
	["Land_Cargo20_blue_F", 250],
	["Land_Cargo20_brick_red_F", 250],
	["Land_Cargo20_cyan_F", 250],
	["Land_Cargo20_grey_F", 250],
	["Land_Cargo20_light_blue_F", 250],
	["Land_Cargo20_light_green_F", 250],
	["Land_Cargo20_military_green_F", 250],
	["Land_Cargo20_orange_F", 250],
	["Land_Cargo20_red_F", 250],
	["Land_Cargo20_sand_F", 250],
	["Land_Cargo20_white_F", 250],
	["Land_Cargo20_yellow_F", 250],
	["Wheeled_APC_F", 30],
	["Tank_F", 30],
	["I_mas_BRDM2", 30],
	["I_mas_BTR60", 40],
	["O_mas_BRDM2", 30],
	["O_mas_BTR60", 40],
	["Rubber_duck_base_F", 10],
	["Boat_Civil_01_base_F", 10],
	["Boat_Armed_01_base_F", 20],
	["Heli_Light_01_base_F", 10],
	["Heli_Light_02_base_F", 20],
	["I_Heli_light_03_base_F", 20],
	["Heli_Transport_01_base_F", 25],
	["Heli_Transport_02_base_F", 30],
	["Heli_Transport_03_base_F", 30],
	["Heli_Transport_04_base_F", 30],
	["Heli_Attack_01_base_F", 10],
	["Heli_Attack_02_base_F", 20]
];


R3F_LOG_CFG_objets_transportables =
[
	["Static_Designator_01_base_F", 2],
	["Static_Designator_02_base_F", 2],
	["StaticWeapon", 5],
	["Box_NATO_AmmoVeh_F", 10],
	["B_supplyCrate_F", 5],
	["ReammoBox_F", 3],
	["Kart_01_Base_F", 5],
	["Quadbike_01_base_F", 10],
	["Rubber_duck_base_F", 10],
	["UAV_01_base_F", 2],
	["Land_BagBunker_Large_F", 10],
	["Land_BagBunker_Small_F", 5],
	["Land_Cargo_Tower_V3_F", 50],
	["Land_Cargo_Tower_V2_F", 50],
	["Land_Cargo_Patrol_V3_F", 25],
	["Land_Cargo_Patrol_V2_F", 25],
	["Land_BagBunker_Tower_F", 7],
	["Land_BagFence_Corner_F", 2],
	["Land_BagFence_End_F", 2],
	["Land_BagFence_Long_F", 3],
	["Land_BagFence_Round_F", 2],
	["Land_BagFence_Short_F", 2],
	["Land_BarGate_F", 3],
	["Land_Canal_WallSmall_10m_F", 4],
	["Land_Canal_Wall_Stairs_F", 3],
	["Land_CargoBox_V1_F", 5],
	["Land_Cargo20_blue_F", 20],
	["Land_Cargo20_brick_red_F", 20],
	["Land_Cargo20_cyan_F", 20],
	["Land_Cargo20_grey_F", 20],
	["Land_Cargo20_light_blue_F", 20],
	["Land_Cargo20_light_green_F", 20],
	["Land_Cargo20_military_green_F", 20],
	["Land_Cargo20_orange_F", 20],
	["Land_Cargo20_red_F", 20],
	["Land_Cargo20_sand_F", 20],
	["Land_Cargo20_white_F", 20],
	["Land_Cargo20_yellow_F", 20],
	["Land_Cargo_Patrol_V1_F", 25],
	["Land_Cargo_Tower_V1_F", 50],
	["Land_CncBarrier_F", 4],
	["Land_CncBarrierMedium_F", 4],
	["Land_CncBarrierMedium4_F", 4],
	["Land_CncShelter_F", 2],
	["Land_CncWall1_F", 3],
	["Land_CncWall4_F", 5],
	["Land_Crash_barrier_F", 5],
	["Land_HBarrierBig_F", 5],
	["Land_HBarrierTower_F", 8],
	["Land_HBarrierWall4_F", 4],
	["Land_HBarrierWall6_F", 6],
	["Land_HBarrier_1_F", 3],
	["Land_HBarrier_3_F", 4],
	["Land_HBarrier_5_F", 5],
	["Land_LampHarbour_F", 2],
	["Land_LampShabby_F", 2],
	["Land_MetalBarrel_F", 2],
	["Land_Mil_ConcreteWall_F", 5],
	["Land_Mil_WallBig_4m_F", 5],
	["Land_Obstacle_Ramp_F", 5],
	["Land_Pipes_large_F", 5],
	["Land_RampConcreteHigh_F", 6],
	["Land_RampConcrete_F", 5],
	["Land_Razorwire_F", 5],
	["Land_Sacks_goods_F", 2],
	["Land_Scaffolding_F", 5],
	["Land_Shoot_House_Wall_F", 3],
	["Land_Stone_8m_F", 5],
	["Land_ToiletBox_F", 2],
	["I_mas_ZU23_AAF", 5],
	["I_mas_DSHKM_AAF", 5],
	["I_mas_DSHkM_Mini_TriPod", 2],
	["I_mas_KORD_AAF", 5],
	["I_mas_KORD_high_AAF", 5],
	["I_mas_AGS_AAF", 5],
	["I_mas_GMG_AAF", 5],
	["I_mas_M2StaticMG_AAF", 5],
	["I_mas_M2StaticMG_MiniTripod_AAF", 2],
	["I_mas_MK19_TriPod_AAF", 5],
	["I_mas_Metis_AAF", 5],
	["I_mas_SPG9_AAF", 5],
	["I_mas_Igla_AA_pod_AAF", 5],
	["I_mas_Stinger_AA_pod_AAF", 5],
	["I_mas_TOW_TriPod_AAF", 5],
	["I_mas_2b14_82mm_AAF", 5],
	["I_mas_M252_AAF", 5],
	["I_mas_D30_AAF", 15],
	["I_mas_D30_AT_AAF", 15],
	["I_mas_M119_AAF", 15],
	["I_mas_M119_AT_AAF", 15],
	["O_mas_ZU23_AAF", 5],
	["O_mas_DSHKM_AAF", 5],
	["O_mas_DSHkM_Mini_TriPod", 2],
	["O_mas_KORD_AAF", 5],
	["O_mas_KORD_high_AAF", 5],
	["O_mas_AGS_AAF", 5],
	["O_mas_Metis_AAF", 5],
	["O_mas_SPG9_AAF", 5],
	["O_mas_Igla_AA_pod_AAF", 5],
	["O_mas_2b14_82mm_AAF", 5],
	["O_mas_D30_AAF", 15],
	["O_mas_D30_AT_AAF", 15],
	["B_mas_GMG_AAF", 5],
	["B_mas_M2StaticMG_AAF", 5],
	["B_mas_M2StaticMG_MiniTripod_AAF", 2],
	["B_mas_MK19_TriPod_AAF", 5],
	["B_mas_Stinger_AA_pod_AAF", 5],
	["B_mas_TOW_TriPod_AAF", 5],
	["B_mas_M252_AAF", 5],
	["B_mas_M119_AAF", 15],
	["B_mas_M119_AT_AAF", 15],
	["B_mas_ZU23_FIA", 5],
	["B_mas_DSHKM_FIA", 5],
	["B_mas_DSHkM_Mini_TriPod_FIA", 2],
	["B_mas_AGS_FIA", 5],
	["B_mas_M2StaticMG_FIA", 5],
	["B_mas_M2StaticMG_MiniTripod_FIA", 2],
	["B_mas_Metis_FIA", 5],
	["B_mas_SPG9_FIA", 5],
	["B_mas_Stinger_AA_pod_FIA", 5],
	["B_mas_2b14_82mm_FIA", 5],
	["B_mas_D30_FIA", 15],
	["B_mas_D30_AT_FIA", 15],
	["Land_BarrelWater_F", 2]
];

/****** MOVABLE-BY-PLAYER OBJECTS / OBJETS DEPLACABLES PAR LE JOUEUR ******/

R3F_LOG_CFG_objets_deplacables =
[
	"StaticWeapon",
	"ReammoBox_F",
	"Kart_01_Base_F",
	"Quadbike_01_base_F",
	"Rubber_duck_base_F",
	"SDV_01_base_F",
	"UAV_01_base_F",
	"Land_BagBunker_Large_F",
	"Land_BagBunker_Small_F",
	"Land_BagBunker_Tower_F",
	"Land_BagFence_Corner_F",
	"Land_BagFence_End_F",
	"Land_BagFence_Long_F",
	"Land_BagFence_Round_F",
	"Land_BagFence_Short_F",
	"Land_BarGate_F",
	"Land_Canal_WallSmall_10m_F",
	"Land_Canal_Wall_Stairs_F",
	"Land_CargoBox_V1_F",
	"Land_Cargo_Patrol_V1_F",
	"Land_Cargo_Patrol_V2_F",
	"Land_Cargo_Patrol_V3_F",
	"Land_Cargo_Tower_V1_F",
	"Land_Cargo_Tower_V2_F",
	"Land_Cargo_Tower_V3_F",
	"Land_Cargo40_blue_F",
	"Land_Cargo40_brick_red_F",
	"Land_Cargo40_cyan_F",
	"Land_Cargo40_grey_F",
	"Land_Cargo40_light_blue_F",
	"Land_Cargo40_light_green_F",
	"Land_Cargo40_military_green_F",
	"Land_Cargo40_red_F",
	"Land_Cargo40_orange_F",
	"Land_Cargo40_sand_F",
	"Land_Cargo40_white_F",
	"Land_Cargo40_yellow_F",
	"Land_Cargo20_blue_F",
	"Land_Cargo20_brick_red_F",
	"Land_Cargo20_cyan_F",
	"Land_Cargo20_grey_F",
	"Land_Cargo20_light_blue_F",
	"Land_Cargo20_light_green_F",
	"Land_Cargo20_military_green_F",
	"Land_Cargo20_red_F",
	"Land_Cargo20_orange_F",
	"Land_Cargo20_sand_F",
	"Land_Cargo20_white_F",
	"Land_Cargo20_yellow_F",
	"Land_CncBarrier_F",
	"Land_CncBarrierMedium_F",
	"Land_CncBarrierMedium4_F",
	"Land_CncShelter_F",
	"Land_CncWall1_F",
	"Land_CncWall4_F",
	"Land_Crash_barrier_F",
	"Land_HBarrierBig_F",
	"Land_HBarrierTower_F",
	"Land_HBarrierWall4_F",
	"Land_HBarrierWall6_F",
	"Land_HBarrier_1_F",
	"Land_HBarrier_3_F",
	"Land_HBarrier_5_F",
	"Land_LampHarbour_F",
	"Land_LampShabby_F",
	"Land_MetalBarrel_F",
	"Land_Mil_ConcreteWall_F",
	"Land_Mil_WallBig_4m_F",
	"Land_Obstacle_Ramp_F",
	"Land_Pipes_large_F",
	"Land_RampConcreteHigh_F",
	"Land_RampConcrete_F",
	"Land_Razorwire_F",
	"I_mas_ZU23_AAF",
	"I_mas_DSHKM_AAF",
	"I_mas_DSHkM_Mini_TriPod",
  "I_mas_KORD_AAF",
	"I_mas_KORD_high_AAF",
	"I_mas_AGS_AAF",
  "I_mas_GMG_AAF",
	"I_mas_M2StaticMG_AAF",
  "I_mas_M2StaticMG_MiniTripod_AAF",
	"I_mas_MK19_TriPod_AAF",
  "I_mas_Metis_AAF",
	"I_mas_SPG9_AAF",
	"I_mas_Igla_AA_pod_AAF",
  "I_mas_Stinger_AA_pod_AAF",
	"I_mas_TOW_TriPod_AAF",
  "I_mas_2b14_82mm_AAF",
	"I_mas_M252_AAF",
	"I_mas_D30_AAF",
  "I_mas_D30_AT_AAF",
	"I_mas_M119_AAF",
	"I_mas_M119_AT_AAF",
  "O_mas_ZU23_AAF",
	"O_mas_DSHKM_AAF",
	"O_mas_DSHkM_Mini_TriPod",
  "O_mas_KORD_AAF",
	"O_mas_KORD_high_AAF",
	"O_mas_AGS_AAF",
  "O_mas_Metis_AAF",
	"O_mas_SPG9_AAF",
	"O_mas_Igla_AA_pod_AAF",
	"O_mas_2b14_82mm_AAF",
	"O_mas_D30_AAF",
	"O_mas_D30_AT_AAF",
  "B_mas_GMG_AAF",
	"B_mas_M2StaticMG_AAF",
  "B_mas_M2StaticMG_MiniTripod_AAF",
	"B_mas_MK19_TriPod_AAF",
  "B_mas_Stinger_AA_pod_AAF",
	"B_mas_TOW_TriPod_AAF",
	"B_mas_M252_AAF",
  "B_mas_M119_AAF",
	"B_mas_M119_AT_AAF",
	"B_mas_ZU23_FIA",
	"B_mas_DSHKM_FIA",
	"B_mas_DSHkM_Mini_TriPod_FIA",
  "B_mas_AGS_FIA",
	"B_mas_M2StaticMG_FIA",
  "B_mas_M2StaticMG_MiniTripod_FIA",
	"B_mas_Metis_FIA",
	"B_mas_SPG9_FIA",
  "B_mas_Stinger_AA_pod_FIA",
	"B_mas_2b14_82mm_FIA",
	"B_mas_D30_FIA",
  "B_mas_D30_AT_FIA",
	"Land_Sacks_goods_F",
	"Land_Scaffolding_F",
	"Land_Shoot_House_Wall_F",
	"Land_Stone_8m_F",
	"Land_ToiletBox_F",
	"Land_BarrelWater_F"
];
