// ******************************************************************************************
// * This project is licensed under the GNU Affero GPL v3. Copyright © 2014 A3Wasteland.com *
// ******************************************************************************************
//	@file Version: 1.1
//	@file Name: serverVars.sqf
//	@file Author: [404] Deadbeat, [404] Costlyy, [404] Pulse, [GoT] JoSchaap, MercyfulFate, AgentRev
//	@file Created: 20/11/2012 05:19
//	@file Args:

if (!isServer && hasInterface) exitWith {};

diag_log "WASTELAND SERVER - Initializing Server Vars";

if (isServer) then
{
	#include "setupServerPVars.sqf"
};

currentStaticHelis = []; // Storage for the heli marker numbers so that we don't spawn wrecks on top of live helis

//Civilian Vehicle List - Random Spawns
civilianVehicles =
[
	"C_Quadbike_01_F",
	"CUP_C_Datsun",
	"CUP_C_Datsun_4seat",
	"CUP_C_Datsun_Covered",
	"CUP_C_Datsun_Plain",
	"CUP_C_Datsun_Tubeframe",
	"CUP_C_Ural_Civ_01",
	"CUP_C_Ural_Civ_02",
	"CUP_C_Ural_Civ_03",
	"CUP_C_Ural_Open_Civ_01",
	"CUP_C_Ural_Open_Civ_02",
	"CUP_C_Ural_Open_Civ_03",
	"CUP_O_UAZ_Unarmed_CHDKZ",
	"CUP_O_UAZ_Unarmed_RU",
	"CUP_O_UAZ_Unarmed_TKA",
	"CUP_O_Ural_CHDKZ",
	"CUP_O_Ural_Empty_CHDKZ",
	"CUP_O_Ural_Empty_RU",
	"CUP_O_Ural_Empty_SLA",
	"CUP_O_Ural_Empty_TKA",
	"CUP_O_Ural_Open_CHDKZ",
	"CUP_O_Ural_Open_RU",
	"CUP_O_Ural_Open_SLA",
	"SUD_TRUCK5t",
	"SUD_TRUCK5t_OPEN",
	"CUP_O_Ural_Open_TKA",
	"CUP_O_Ural_RU",
	"CUP_O_Ural_Reammo_CHDKZ",
	"CUP_O_Ural_Reammo_RU",
	"CUP_O_Ural_Reammo_SLA",
	"CUP_O_Ural_Reammo_TKA",
	"CUP_O_Ural_Refuel_CHDKZ",
	"CUP_O_Ural_Refuel_RU",
	"CUP_O_Ural_Refuel_SLA",
	"CUP_O_Ural_Refuel_TKA",
	"CUP_O_Ural_Repair_CHDKZ",
	"CUP_O_Ural_Repair_RU",
	"CUP_O_Ural_Repair_SLA",
	"CUP_O_Ural_Repair_TKA",
	"CUP_O_Ural_SLA",
	"CUP_O_Ural_TKA",
	"PMC_Offroad_Transport",
	"PMC_Offroad_Transport_B",
	"PMC_Offroad_Cargo_B",
	"PMC_Offroad_Cargo",
	"C_Offroad_01_F",
	"I_G_Offroad_01_F",
	"C_Van_01_box_F",
	"C_Van_01_transport_F"
];

//Light Military Vehicle List - Random Spawns
lightMilitaryVehicles =
[
	"CUP_B_UAZ_AGS30_ACR",
	"CUP_B_UAZ_AGS30_CDF",
	"CUP_B_UAZ_MG_ACR",
	"CUP_B_UAZ_MG_CDF",
	"CUP_B_UAZ_Open_ACR",
	"CUP_B_UAZ_Open_CDF",
	"CUP_B_UAZ_SPG9_ACR",
	"CUP_B_UAZ_SPG9_CDF",
	"CUP_B_Ural_ZU23_CDF",
	"CUP_B_ZSU23_CDF",
	"CUP_I_Datsun_PK",
	"CUP_I_Datsun_PK_Random",
	"CUP_I_Datsun_PK_TK",
	"CUP_I_Datsun_PK_TK_Random",
  "PMC_Offroad_Armed",
  "PMC_Offroad_Armed_B",
	"CUP_I_UAZ_AGS30_UN",
	"CUP_I_UAZ_MG_UN",
	"CUP_I_UAZ_Open_UN",
	"CUP_I_UAZ_SPG9_UN",
	"CUP_O_Datsun_PK",
	"CUP_O_Datsun_PK_Random",
	"CUP_O_LR_MG_TKA",
	"CUP_O_LR_MG_TKM",
	"CUP_O_LR_SPG9_TKA",
	"CUP_O_LR_SPG9_TKM",
	"CUP_O_UAZ_AGS30_CHDKZ",
	"CUP_O_UAZ_AGS30_RU",
	"CUP_O_UAZ_AGS30_TKA",
	"CUP_O_UAZ_MG_CHDKZ",
	"CUP_O_UAZ_MG_RU",
	"CUP_O_UAZ_MG_TKA",
	"CUP_O_UAZ_Open_CHDKZ",
	"CUP_O_UAZ_Open_RU",
	"CUP_O_UAZ_Open_TKA",
	"CUP_O_UAZ_SPG9_CHDKZ",
	"CUP_O_UAZ_SPG9_RU",
	"CUP_O_UAZ_SPG9_TKA",
//	"O_Truck_02_covered_F",
//	"I_Truck_02_covered_F",
//	"O_Truck_02_transport_F",
//	"I_Truck_02_transport_F",
	"I_G_Offroad_01_armed_F"
];

//Medium Military Vehicle List - Random Spawns
mediumMilitaryVehicles =
[
//	"I_Truck_02_Fuel_F",
//	"O_Truck_02_Fuel_F",
//	"I_Truck_02_medical_F",
//	"O_Truck_02_medical_F",
	"CUP_O_Ural_ZU23_CHDKZ",
	"CUP_O_Ural_ZU23_RU",
	"CUP_O_Ural_ZU23_SLA",
	"CUP_O_Ural_ZU23_TKA",
	"CUP_O_Ural_ZU23_TKM",
	"CUP_O_UAZ_SPG9_CHDKZ",
	"CUP_O_UAZ_SPG9_RU",
	"CUP_O_UAZ_SPG9_TKA",
	"CUP_B_Dingo_Des",
	"CUP_B_Dingo_GL_Des",
	"CUP_B_Dingo_GL_Wdl",
	"CUP_B_Dingo_Wdl",
	"CUP_B_HMMWV_AGS_GPK_ACR",
	"CUP_B_LAV25M240_USMC",
	"CUP_B_LR_MG_GB_W",
	"CUP_B_M113_USA",
	"CUP_B_M163_USA",
	"CUP_B_HMMWV_Ambulance_ACR",
	"CUP_B_HMMWV_Ambulance_USA",
	"CUP_B_HMMWV_Ambulance_USMC",
	"CUP_B_HMMWV_Avenger_USA",
	"CUP_B_HMMWV_Avenger_USMC",
	"CUP_B_HMMWV_Crows_M2_USA",
	"CUP_B_HMMWV_Crows_MK19_USA",
	"CUP_B_HMMWV_DSHKM_GPK_ACR",
	"CUP_B_HMMWV_M1114_USMC",
	"CUP_B_HMMWV_M2_GPK_ACR",
	"CUP_B_HMMWV_M2_GPK_USA",
	"CUP_B_HMMWV_M2_USA",
	"CUP_B_HMMWV_M2_USMC",
	"CUP_B_HMMWV_MK19_USA",
	"CUP_B_HMMWV_MK19_USMC",
	"CUP_B_HMMWV_SOV_USA",
	"CUP_B_HMMWV_TOW_USA",
	"CUP_B_HMMWV_TOW_USMC",
	"CUP_B_HMMWV_Terminal_USA",
	"CUP_B_HMMWV_Transport_USA",
	"CUP_B_HMMWV_Unarmed_USA",
	"CUP_B_HMMWV_Unarmed_USMC"
];

//Heavy Military Vehicle List - Random Spawns - rare
heavyMilitaryVehicles =
[
// BMPs

	 "CUP_B_LAV25M240_USMC",
	 "CUP_B_LAV25_HQ_USMC",
	 "CUP_B_LAV25_USMC",
	 "I_mas_BMP2_HQ_AAF_01",
	 "I_mas_BMP2_Ambul_01",
	 "O_mas_BMP1_OPF_01",
	 "O_mas_BMP1P_OPF_01",
	 "O_mas_BMP2_OPF_01",
	 "O_mas_BMP2_HQ_OPF_01",
	 "O_mas_BMP2_Ambul_01",
	 // BRDM2
	 "CUP_I_BRDM2_ATGM_NAPA",
	 "CUP_I_BRDM2_ATGM_TK_Gue",
	 "CUP_I_BRDM2_HQ_NAPA",
	 "CUP_I_BRDM2_HQ_TK_Gue",
	 "CUP_I_BRDM2_HQ_UN",
	 "CUP_I_BRDM2_NAPA",
	 "CUP_I_BRDM2_TK_Gue",
	 "CUP_I_BRDM2_UN",
	 // Tanks
	 "CUP_O_T55_TK",
   "CUP_O_T72_CHDKZ",
   "CUP_O_T72_RU",
   "CUP_O_T72_SLA",
   "CUP_O_T72_TKA",
	 "CUP_O_ZSU23_ChDKZ",
   "CUP_O_ZSU23_SLA",
   "CUP_O_ZSU23_TK",
	 "CUP_O_M113_Med_TKA",
	 "CUP_O_M113_TKA",
	 "CUP_B_M1A1_DES_USMC",
	 "CUP_B_M1A1_DES_US_Army",
	 "CUP_B_M1A1_Woodland_USMC",
	 "CUP_B_M1A1_Woodland_US_Army",
	 "CUP_B_M1A2_TUSK_MG_DES_USMC",
	 "CUP_B_M1A2_TUSK_MG_DES_US_Army",
	 "CUP_B_M1A2_TUSK_MG_USMC",
	 "CUP_B_M1A2_TUSK_MG_US_Army",
	 "CUP_B_M270_DPICM_USA",
	 "CUP_B_M270_DPICM_USMC",
	 "CUP_B_M270_HE_USA",
	 "CUP_B_M270_HE_USMC",
	 "CUP_B_M113_USA",
	 "CUP_B_M163_USA"



];

//Water Vehicles - Random Spawns
waterVehicles =
[
//	"B_Lifeboat",
//	"O_Lifeboat",
//	"C_Rubberboat",
	"B_SDV_01_F",
	"O_SDV_01_F",
	"I_SDV_01_F",
//	"B_Boat_Transport_01_F",
//	"O_Boat_Transport_01_F",
//	"I_Boat_Transport_01_F",
//	"I_G_Boat_Transport_01_F",
	"B_Boat_Armed_01_minigun_F",
	"O_Boat_Armed_01_hmg_F",
	"GNT_C185F",
	"CUP_C_Fishing_Boat_Chernarus",
	"CUP_B_Zodiac_USMC",
	"CUP_B_RHIB_USMC",
	"CUP_B_RHIB2Turret_USMC",
	"I_Boat_Armed_01_minigun_F",
	"C_Boat_Civil_01_F",
	"C_Boat_Civil_01_police_F",
	"C_Boat_Civil_01_rescue_F"
];

//Essential List - Random Spawns.
essentialsList =
[
	"B_supplyCrate_F"

];

//Object List - Random Spawns.
objectList =
[
	"CamoNet_INDP_open_F",
	"CamoNet_INDP_open_F",
	"Land_BagBunker_Large_F",
	"Land_BagBunker_Large_F",
	"Land_BagBunker_Small_F",
	"Land_BagBunker_Small_F",
	"Land_BagBunker_Tower_F",
	"Land_BagBunker_Tower_F",
	"Land_BarGate_F",
	"Land_Canal_Wall_Stairs_F",
	"Land_Canal_WallSmall_10m_F",
	"Land_Canal_WallSmall_10m_F",
	"Land_CncBarrierMedium4_F",
	"Land_CncShelter_F",
	"Land_Pod_Heli_Transport_04_bench_F",
	"Land_Pod_Heli_Transport_04_covered_F",
	"Land_Pod_Heli_Transport_04_fuel_F",
	"Land_Pod_Heli_Transport_04_medevac_F",
	"Land_Pod_Heli_Transport_04_repair_black_F",
	"Land_Pod_Heli_Transport_04_bench_black_F",
	"Land_Pod_Heli_Transport_04_covered_black_F",
	"Land_Pod_Heli_Transport_04_fuel_black_F",
	"Land_Pod_Heli_Transport_04_medevac_black_F",
	"Land_Pod_Heli_Transport_04_repair_black_F",
	"Land_CncWall4_F",
	"Land_HBarrier_1_F",
	//"Land_Cargo40_blue_F",
	//"Land_Cargo40_brick_red_F",
	//"Land_Cargo40_cyan_F",
	//"Land_Cargo40_grey_F",
	//"Land_Cargo40_light_blue_F",
	//"Land_Cargo40_light_green_F",
	//"Land_Cargo40_military_green_F",
	//"Land_Cargo40_red_F",
	//"Land_Cargo40_orange_F",
	//"Land_Cargo40_sand_F",
	//"Land_Cargo40_white_F",
	//"Land_Cargo40_yellow_F",
	//"Land_Cargo20_blue_F",
	//"Land_Cargo20_brick_red_F",
	//"Land_Cargo20_cyan_F",
	//"Land_Cargo20_grey_F",
	//"Land_Cargo20_light_blue_F",
	//"Land_Cargo20_light_green_F",
	//"Land_Cargo20_military_green_F",
	//"Land_Cargo20_red_F",
	//"Land_Cargo20_orange_F",
	//"Land_Cargo20_sand_F",
	//"Land_Cargo20_white_F",
	//"Land_Cargo20_yellow_F",
	"Land_HBarrier_3_F",
	"Land_HBarrier_5_F",
	"Land_HBarrier_5_F",
	"Land_HBarrier_5_F",
	"Land_HBarrierBig_F",
	"Land_HBarrierBig_F",
	"Land_HBarrierBig_F",
	"Land_HBarrierBig_F",
	"Land_HBarrierTower_F",
	"Land_HBarrierWall4_F",
	"Land_HBarrierWall4_F",
	"Land_HBarrierWall6_F",
	"Land_HBarrierWall6_F",
	"Land_MetalBarrel_F",
	"Land_Mil_ConcreteWall_F",
	"Land_Mil_WallBig_4m_F",
	"Land_Mil_WallBig_4m_F",
	"Land_Mil_WallBig_4m_F",
	"Land_Pipes_large_F",
	"Land_RampConcrete_F",
	"Land_RampConcreteHigh_F",
	"Land_Shoot_House_Wall_F"
];

//Object List - Random Spawns.
staticWeaponsList =
[
	"B_Mortar_01_F",
	"O_Mortar_01_F",
	"I_Mortar_01_F",
	"I_G_Mortar_01_F"
];

//Object List - Random Helis.
staticHeliList =
[

  "CUP_B_AH1Z",
	"CUP_B_CH47F_USA",
	"CUP_B_CH53E_USMC",
	"CUP_B_AW159_Unarmed_BAF",
	"CUP_B_Mi171Sh_Unarmed_ACR",
	"CUP_B_MV22_USMC",
	"CUP_B_MH60S_FFV_USMC",
	"CUP_B_Mi17_medevac_CDF",
	"CUP_B_Mi35_CZ",
	"CUP_B_UH60M_FFV_US",
	"CUP_B_UH60L_Unarmed_FFV_US",
	"CUP_Merlin_HC3_FFV",
	"CUP_O_Mi8_CHDKZ",
	"CUP_O_Mi8_SLA_2",
	"SUD_MI8",
	"SUD_UH60",
	"Cobra2",
	"Cobra1",
	"Cobra3",
	"AH1W_2",
	"AH1W",
	"Bell412",
	"UH1C",
	"UH1C_HH",
	"uh1h_Shark",
	"uh1c_miniguns",
	"UH1H_Gun",
	"UH1C_XM16AS",
	"UH1C_XM21AS",
	"UH1D_1",
	"UH1H_Closed",
	"UH1H_FFV",
	"UH1H_Gunship",
	"UH1H_LMG",
	"UH1H_Medevac",
	"UH1H_rockets",
	"UH1H_Transport",
	"UH1N_Black",
	"UH1N_Escort",
	"UH1N_Gau_Gatling",
	"UH1N_Bulletstorm",
	"UH1N_Gunship",
	"UH1N_Hydra",
	"UH1N_Iroquois",
	"UH1N_Slick",
	"UH1N_TOW",
	"UH1Y_FFV",
	"UH1Y_TOW",
	"UH1Y_Venom_50Cal",
	"UH1Y_Venom",
	"PMC_MH9",
	"PMC_MH9_B",
	"I_Heli_light_03_unarmed_F"
	// don't put cargo helicopters here, it doesn't make sense to find them in towns; they spawn in the CivHeli mission
];

//Object List - Random Planes.
staticPlaneList =
[
 "GNT_C185T",
 "GNT_C185",
 "sab_camel_ind",
 "sab_camel_ind_B"
];

//Random Weapon List - Change this to what you want to spawn in cars.
vehicleWeapons =
[
//	"hgun_P07_F",
//	"hgun_Rook40_F",
//	"hgun_ACPC2_F",
//	"arifle_SDAR_F",
	"SMG_01_F",	// Vermin .45 ACP
	"SMG_02_F",	// Sting 9mm
	"hlc_rifle_ak74",
  "hlc_rifle_aks74",
  "hlc_rifle_aks74u",
  "hlc_rifle_ak47",
	"hlc_rifle_ak74_dirty",
	"hlc_rifle_g3a3",
	"hlc_rifle_g3ka4",
	"HLC_Rifle_g3ka4_GL",
	"hlc_rifle_g3sg1",
	"hlc_rifle_hk51",
	"hlc_rifle_hk53",
	"hlc_rifle_psg1",
	"hlc_rifle_samr2",
	"hlc_lmg_m60",
	"hlc_lmg_M60E4",
	"hlc_smg_mp5a2",
	"hlc_smg_mp5a3",
	"hlc_smg_mp5k_PDW",
	"hlc_smg_mp5k",
	"hlc_smg_mp5a4",
	"hlc_smg_mp5n",
	"hlc_smg_mp510",
	"hlc_smg_mp5sd5",
	"hlc_smg_mp5sd6",
	"hlc_smg_9mmar",
	"hlc_rifle_STGW57",
	"hlc_rifle_stgw57_RIS",
	"hlc_rifle_stgw57_commando",
	"hlc_rifle_sig5104",
	"hlc_rifle_amt",
	"hlc_optic_Kern",
	"hlc_optic_Kern2d",
	"hlc_rifle_G36A1",
	"hlc_rifle_G36A1AG36",
	"hlc_rifle_G36KA1",
	"hlc_rifle_G36C",
	"hlc_rifle_G36E1",
	"hlc_rifle_G36E1AG36",
	"hlc_rifle_G36KE1",
	"hlc_rifle_G36V",
	"hlc_rifle_G36KV",
	"hlc_rifle_G36CV",
	"hlc_rifle_G36VAG36",
	"hlc_rifle_G36TAC",
	"hlc_rifle_G36KTAC",
	"hlc_rifle_G36CTAC",
	"hlc_rifle_G36MLIC",
	"hlc_rifle_G36KMLIC",
	"hlc_rifle_G36CMLIC",
	"hlc_rifle_G36MLIAG36",
	"hlc_rifle_M1903A1_unertl",
	"hlc_rifle_M1903A1",
	"GG_Weaponpack_M1_Garand",
	"hlc_rifle_aug",
	"hlc_rifle_auga1_B",
	"hlc_rifle_auga1carb",
	"hlc_rifle_auga1carb_b",
	"hlc_rifle_aughbar",
	"hlc_rifle_aughbar_b",
	"hlc_rifle_augpara",
	"hlc_rifle_augpara_b",
	"hlc_rifle_auga2",
	"hlc_rifle_auga2_b",
	"hlc_rifle_auga2carb",
	"hlc_rifle_auga2carb_b",
	"hlc_rifle_auga2lsw",
	"hlc_rifle_auga2lsw_b",
	"hlc_rifle_auga2para",
	"hlc_rifle_auga2para_b",
	"hlc_rifle_augsr",
	"hlc_rifle_augsr_b",
	"hlc_rifle_augsrcarb",
	"hlc_rifle_augsrcarb_b",
	"hlc_rifle_augsrhbar",
	"hlc_rifle_augsrhbar_b",
	"hlc_rifle_auga3",
	"hlc_rifle_auga3_bl",
	"hlc_rifle_auga3_b",
	"hlc_rifle_auga3_GL",
	"hlc_rifle_auga3_GL_BL",
	"hlc_rifle_auga3_GL_B",
	"hlc_lmg_minimipara",
	"hlc_lmg_minimi",
	"hlc_lmg_minimi_railed",
	"hlc_lmg_m249para",
	"hlc_lmg_M249E2",
	"hlc_m249_pip1",
	"hlc_m249_pip2",
	"hlc_m249_pip3",
	"hlc_m249_pip4",
	"hlc_rifle_awcovert",
	"hlc_rifle_awcovert_BL",
	"hlc_rifle_awcovert_FDE",
	"hlc_rifle_awmagnum",
	"hlc_rifle_awmagnum_BL",
	"hlc_rifle_awmagnum_FDE",
	"hlc_rifle_awMagnum_FDE_ghillie",
	"hlc_rifle_awMagnum_BL_ghillie",
	"hlc_rifle_awMagnum_OD_ghillie",
	"CUP_srifle_AS50",
	"CUP_srifle_AWM_wdl",
	"CUP_arifle_AK107",
	"CUP_sgun_AA12",
	"CUP_arifle_MG36",
	"CUP_srifle_CZ550",
	"CUP_srifle_LeeEnfield",
	"CUP_arifle_M16A2",
	"CUP_arifle_M16A2_GL",
	"CUP_arifle_M4A1",
	"CUP_arifle_M4A1_camo",
	"CUP_srifle_M40A3",
	"CUP_lmg_M240",
	"CUP_lmg_M249",
	"CUP_sgun_M1014",
	"CUP_smg_MP5SD6",
	"CUP_smg_MP5A5",
	"CUP_lmg_PKM",
	"CUP_arifle_Sa58P",
	"CUP_arifle_Sa58V",
	"CUP_sgun_Saiga12K",
	"CUP_arifle_Mk16_CQC",
	"CUP_lmg_L110A1",
	"CUP_arifle_L85A2",
	"CUP_srifle_M107_Base",
	"CUP_arifle_M16A4_Base",
	"CUP_arifle_M16A4GL",
	"CUP_arifle_M4A1_BUIS_GL",
	"CUP_arifle_M4A1_BUIS_camo_GL",
	"CUP_arifle_M4A1_black",
	"CUP_srifle_Mk12SPR",
	"CUP_lmg_M249_para",
	"CUP_lmg_Mk48_wdl",
	"CUP_arifle_Mk16_SV",
	"CUP_arifle_Mk17_CQC",
	"CUP_arifle_Mk17_CQC_FG",
	"CUP_arifle_Mk17_STD",
	"CUP_arifle_Mk20",
	"CUP_arifle_XM8_Compact_Rail",
	"CUP_arifle_XM8_Railed",
	"CUP_arifle_Mk16_STD_FG",
	"CUP_arifle_Mk16_STD",
	"CUP_arifle_Mk16_CQC_FG",
	"CUP_smg_EVO",
	"CUP_lmg_UK59",
	"CUP_arifle_XM8_Carbine",
	"CUP_arifle_XM8_Compact",
	"CUP_arifle_xm8_SAW",
	"CUP_arifle_xm8_sharpshooter",
	"CUP_arifle_CZ805_A1",
	"CUP_arifle_CZ805_GL",
	"CUP_arifle_CZ805_B_GL",
	"CUP_arifle_CZ805_B",
	"CUP_srifle_DMR",
	"CUP_srifle_M110",
	"CUP_srifle_M14",
	"CUP_srifle_M24_wdl",
	"CUP_srifle_M24_ghillie",
	"CUP_lmg_Pecheneg",
	"CUP_arifle_Sa58RIS1",
	"CUP_arifle_Sa58RIS2",
	"CUP_srifle_SVD",
	"CUP_srifle_VSSVintorez",
	"hlc_rifle_akm",
  "hlc_rifle_rpk",
  "hlc_rifle_ak12",
  "hlc_rifle_akmgl",
  "hlc_rifle_aks74_GL",
  "hlc_rifle_saiga12k",
  "hlc_rifle_aek971",
  "hlc_rifle_RU556",
  "hlc_rifle_RU5562",
  "hlc_rifle_Colt727",
  "hlc_rifle_Colt727_GL",
  "hlc_rifle_bcmjack",
  "hlc_rifle_Bushmaster300",
  "hlc_rifle_vendimus",
  "hlc_rifle_SAMR",
  "hlc_rifle_honeybase",
  "hlc_rifle_honeybadger",
  "hlc_rifle_M14",
  "hlc_rifle_M21",
  "hlc_rifle_M14DMR",
  "hlc_rifle_m14sopmod",
  "hlc_rifle_l1a1slr",
  "hlc_rifle_SLR",
  "hlc_rifle_STG58F",
  "hlc_rifle_FAL5061",
  "hlc_rifle_c1A1",
  "hlc_rifle_LAR",
  "hlc_rifle_SLRchopmod",
  "hlc_rifle_falosw",
  "hlc_rifle_osw_GL",
	"hgun_mas_mp7_F",
	"hgun_mas_mp7p_F",
	"tf47_m3maaws",
	"tf47_smaw",
	"tf47_at4_heat",
	"tf47_at4_hedp",
	"tf47_at4_hp",
	"RH_deagle",
	"RH_deagleg",
	"RH_deagles",
	"RH_deaglem",
	"RH_cz75",
	"RH_sw659",
	"RH_usp",
	"RH_mak",
	"RH_m1911",
	"RH_kimber",
	"RH_kimber_nw",
	"RH_uspm",
	"RH_m9",
	"RH_m9c",
	"RH_vz61",
	"RH_g18",
	"RH_g17",
	"RH_tt33",
	"RH_mk2",
	"RH_p226",
	"RH_p226s",
	"RH_g19",
	"RH_g19t",
	"RH_vp70",
	"RH_mateba",
	"RH_python",
	"RH_mp412",
	"RH_bull",
	"RH_bullb",
	"RH_ttracker",
	"RH_ttracker_g",
	"RH_fnp45",
	"RH_fnp45t",
	"RH_fn57",
	"RH_fn57_g",
	"RH_fn57_t",
	"RH_gsh18",
	"RH_tec9",
	"RH_muzi",
	"arifle_MXC_F",
	"arifle_MX_F",
	"arifle_MX_GL_F",
	"arifle_MX_SW_F",
	"arifle_MXM_F"
];

vehicleAddition =
[
	"muzzle_snds_L", // 9mm
	"muzzle_snds_M", // 5.56mm
	"muzzle_snds_H", // 6.5mm
	"muzzle_snds_H_MG", // 6.5mm LMG
	"muzzle_snds_B", // 7.62mm
	"muzzle_snds_acp", // .45 ACP
	// AK attachments
	"HLC_Optic_PSO1",
	"HLC_Optic_1p29",
	"hlc_muzzle_545SUP_AK",
	"hlc_muzzle_762SUP_AK",
	"hlc_optic_kobra",
	"hlc_optic_goshawk",
	// FAL, G3, and M14 attachments
	"hlc_optic_PVS4FAL",
	"hlc_optic_suit",
	"hlc_muzzle_snds_fal",
	"hlc_muzzle_snds_HK33",
	"hlc_muzzle_snds_G3",
	"HLC_Optic_ZFSG1",
	"hlc_muzzle_snds_M14",
	"hlc_optic_artel_m14",
	// AR15 attachments
	"hlc_muzzle_556NATO_KAC",
	"hlc_muzzle_300blk_KAC",
	// MP5 attachments
	"hlc_muzzle_Agendasix",
	"hlc_muzzle_Tundra",
	"hlc_muzzle_Agendasix10mm",
	// AUG attachments
	"hlc_barrel_standard",
	"hlc_barrel_carbine",
	"hlc_barrel_hbar",
	"hlc_barrel_9mm",
	"hlc_muzzle_snds_AUG",
	"hlc_muzzle_snds_a6AUG",
  // SIG SG510s Attachments
	"hlc_optic_Kern",
	"tf47_optic_smaw",
	"tf47_optic_m3maaws",
	"hlc_optic_Kern2d",
	// LMG attachments
	"tf47_optic_m3maaws",
	"tf47_optic_smaw",
	"CUP_muzzle_PBS4",
  "CUP_muzzle_PB6P9",
  "CUP_muzzle_Bizon",
  "CUP_muzzle_snds_M110",
  "CUP_muzzle_snds_M14",
  "CUP_muzzle_snds_M9",
  "CUP_muzzle_snds_MicroUzi",
  "CUP_muzzle_snds_AWM",
  "CUP_muzzle_snds_G36_black",
  "CUP_muzzle_snds_G36_desert",
  "CUP_muzzle_snds_L85",
  "CUP_muzzle_snds_M16_camo",
  "CUP_muzzle_snds_M16",
  "CUP_muzzle_snds_SCAR_L",
  "CUP_muzzle_mfsup_SCAR_L",
  "CUP_muzzle_snds_SCAR_H",
  "CUP_muzzle_mfsup_SCAR_H",
  "CUP_muzzle_snds_XM8",
	"ACE_optic_Arco_2D",
	"ACE_optic_Hamr_2D",
	"ACE_optic_SOS_2D",
	"ACE_optic_MRCO_2D",
	"ACE_acc_pointer_red",
	"CUP_optic_PSO_1",
  "CUP_optic_PSO_3",
  "CUP_optic_Kobra",
  "CUP_optic_GOSHAWK",
  "CUP_optic_NSPU",
  "CUP_optic_PechenegScope",
  "CUP_optic_MAAWS_Scope",
  "CUP_optic_SMAW_Scope",
  "CUP_optic_AN_PAS_13c2",
  "CUP_optic_LeupoldMk4",
  "CUP_optic_HoloBlack",
  "CUP_optic_HoloWdl",
  "CUP_optic_HoloDesert",
  "CUP_optic_Eotech533",
  "CUP_optic_CompM4",
  "CUP_optic_SUSAT",
  "CUP_optic_ACOG",
  "CUP_optic_CWS",
  "CUP_optic_Leupold_VX3",
  "CUP_optic_AN_PVS_10",
  "CUP_optic_CompM2_Black",
  "CUP_optic_CompM2_Woodland",
  "CUP_optic_CompM2_Woodland2",
  "CUP_optic_CompM2_Desert",
  "CUP_optic_RCO",
  "CUP_optic_RCO_desert",
  "CUP_optic_LeupoldM3LR",
  "CUP_optic_LeupoldMk4_10x40_LRT_Desert",
  "CUP_optic_LeupoldMk4_10x40_LRT_Woodland",
  "CUP_optic_ElcanM145",
  "CUP_optic_AN_PAS_13c1",
  "CUP_optic_LeupoldMk4_CQ_T",
  "CUP_optic_ELCAN_SpecterDR",
  "CUP_optic_LeupoldMk4_MRT_tan",
  "CUP_optic_SB_11_4x20_PM",
  "CUP_optic_ZDDot",
  "CUP_optic_MRad",
	"CUP_optic_TrijiconRx01_desert",
  "CUP_optic_TrijiconRx01_black",
  "CUP_optic_AN_PVS_4",
	"RH_demz",
	"RH_gemtech9",
	"RH_A26",
	"RH_suppr9",
	"RH_aacusp",
	"RH_gemtech45",
	"RH_osprey",
	"ACRE_PRC343",
	"ACRE_PRC77",
	"ACRE_PRC117F",
	"ACRE_PRC152",
	"ACRE_PRC148",
	"RH_fhusp",
	"RH_x2",
	"RH_m6x",
	"RH_x300",
	"RH_pmsd",
	"RH_pmir",
	"RH_matchsd",
	"RH_m9qd",
	"RH_vp70stock",
	"RH_docter",
	"RH_sfn57",
	"RH_tecsd",
	"RH_muzisd",
	"optic_SOS",
	"optic_Aco",
	"optic_ACO_grn",
	"optic_aco_smg",
	"optic_Holosight",
	"optic_Holosight_smg",
	"ACE_DefusalKit",
	"ACE_Clacker",
	"ACE_M26_Clacker",
	"ACE_HuntIR_monitor",
	"ACE_TacticalLadder_Pack",
	"ACE_Sandbag_empty",
	"ACE_RangeCard",
	"ACE_SpareBarrel",
	"ACE_wirecutter",
	"ACE_EarPlugs",
	//"ACE_quikclot", //Advanced
	//"ACE_fieldDressing", //Advanced
	"acc_flashlight",
	//"ACE_elasticBandage", //Advanced
	//"ACE_tourniquet", //Advanced
	"ACE_bodybag",
	"ACE_MapTools",
	"acc_flashlight",
	"acc_pointer_IR",
	"Medikit",
	"Medikit",
	"FirstAidKit",
	"ToolKit"

];

vehicleAddition2 =
[
	"Chemlight_blue",
	"Chemlight_green",
	"ACE_HandFlare_White",
	"ACE_HandFlare_Red",
	"ACE_HandFlare_Green",
	"ACE_HuntIR_M203",
	"ACE_HandFlare_Yellow",
	"ACE_M84",
	"Chemlight_yellow",
	"Chemlight_red"
];
